services:
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 15432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
