// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Greeting struct {
	ID        string
	Message   pgtype.Text
	CreatedAt pgtype.Timestamp
}
