// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: lock.sql

package db

import (
	"context"
)

const tryAdvisoryLock = `-- name: TryAdvisoryLock :one
SELECT pg_try_advisory_xact_lock(hashtext($1))
`

func (q *Queries) TryAdvisoryLock(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLock, key)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
